let peopleArr = [
    "Donald Trump",
    "Barack Obama",
    "Greta Thunberg",
    "Pope Francis",
    "Osama Bin Laden",
    "Tony Blair",
    "Angela Merkel",
    "J.K.Rowling",
    "Kim Jong Un",
    "Usain Bolt",
    "Stephen Hawking",
    "Linus Torvalds",
    "George W. Bush",
    "Jeb Bush",
    "Joe Biden",
    "Jimmy Wales",
    "Steve Jobs",
    "Hilary Clinton",
    "Queen Elizabeth II",
    "Jimmy Carter",
    "George Clooney",
    "Oprah Winfrey",
    "Tim Berners-Lee",
    "Lance Armstrong",
    "Prince William",
    "Kate Middleton",
    "Messi",
    "Alex Jones",
    "Al Gore",
    "Hilary Clinton",
    "Emma Watson",
    "Beyonce",
    "Lady Gaga",
    "Angelina Jolie",
    "Vladimir Putin",
    "David Cameron",
    "Will Smith",
    "Larry Page",
    "Angelina Jolie",
    "Ivanka Trump",
    "Shakira",
    "Serena Williams",
    "Michael Bloomberg",
    "Mark Zuckerberg",
    "Elon Musk",
    "Sacha Baron Cohen",
    "Jon Stewart",
    "Scarlett Johansson",
    "Stephen Colbert",
    "Prince Charles",
    "Bashar Assad",
    "E.L. James",
    "Rihanna",
    "Warren Buffett",
    "Xi Jinping",
    "Prince Harry",
    "Meghan Markle",
    ];
    
    let placeArr = [
    "house",
    "bar",
    "dressing Room",
    "Burger King",
    "bedroom",
    "living room",
    "airport",
    "apartment building",
    "bank",
    "barber shop",
    "book store",
    "bowling alley",
    "bus stop",
    "church",
    "convenience store",
    "department store",
    "fire department",
    "gas station",
    "hospital",
    "house",
    "library",
    "movie theater",
    "museum",
    "office building",
    "post office",
    "restaurant",
    "school",
    "mall",
    "supermarket",
    "train station",
    "rally",
    ];
    
    let actionArr = [
    "sleeping",
    "driving",
    "Halloween",
    "Christmas",
    "Easter",
    "Sunday School",
    "watching TV",
    "playing video games",
    "working",
    "reading Gex quotes",
    "watching the History Channel",
    "listening to Lo-Fi Beats",
    "gambling",
    "drinking",
    "having a pleasant evening",
    "dating",
    "a wedding",
    "smoking weed"
    ];


 module.exports = {peopleArr, actionArr, placeArr};