const bubsyArr = [
    "What could possibly go wrong?",
    "Did I mention I don't like heights?",
    "More like a bridge too short.",
    "Hey, whatever blows your hair back!",
    "Hey, I thought I saw Elvis back there!",
    "Shouldn't that be 'fearless'? Uh-oh...",
    "Well, it worked for Clint.",
    "Go ahead, make my day!",
    "My contract does not mention pain!",
    "Hey, I didn't write this stuff!!!",
    "Next time, I get a stunt-cat!",
    "Is there a veterinarian in the audience?",
    "That's it! I'm outta here! You can't make me.",
    "What, and give up show business?",
    "Somebody dial 911!!!",
    "Whoah, are you still playing this thing?!",
    "Is there a veterinarian in the house?",
    "What could possibly go wrong?",
    "Nothing can stop me now!",
    "Pilot's license? What for?",
    "Oh sure, let's all torture the Bubster.",
    "Now, what would a platform game be without platforms hmm. I wonder if there's any extra lives up there?",
    "One woolie out, and a lot more to go!",
    "Whatever blows your hair back.",
    "Wow, you're still playing this game?",
    "Would some call 911!",
    "Hey how did I end up in Triassic Park?",
    "Hmm, now what would a platform game be without platforms hmm. I wonder if there's any extra lives up there?",
    "Gimme, gimme gimme!",
    "So you wanna be a video game star! For starters, grab all the atoms you see! There's plenty of them in each level, and if you get enough of them. You'll be in it for some prizes!",
    "Oh look an arrow! Aren't these game designer wonderful? Giving you a guide post to help your way how convenient!",
    "Woo hoo! Now if you lose a Bubsy, you start over here instead of at the beginning of the level ain't life grand?",
    "See that thing in front of you? That's a switch, just run into it to make something cool happen!",
    "Oh, oh, this is my favorite part, hold the square button when you walk up to an atom! Go ahead, try it but don't hold it too long!",
    "Come one, come all, don't be shy! Step right up and win valuable prizes! Shoot the Woolie with the atom!",
    "Hey, once I rack this power up, Bubsy smash too-lie Woolies.",
    "Two points! You're not so tough!",
    "Woo, woo, woo, woo, woo! Sting like a bee!",
    "Tag you're it!",
    "Woo hoo! He shoots he scores!",
    'It slices it dices, easy picking!',
    "It's just too easy!",
    "You did read the instructions didn't you?",
    "Hey! What buttons did you press?",
    "Hey! I'm walking here!",
    "Get me my attorney!",
    "Houston, we have a problem!",
    "Good thing I'm a cartoon!",
    "Oh what's the number for 911?",
    "Good thing I'm under the contract.",
    "Here we go again! I hope you know what you're doing?",
    "It's gonna be a bumpy ride!",
    "Keep your arms and legs inside until this ride comes to a full and complete stop!",
    "I don't think we're in Kansas anymore!",
    'Ah this will come in handy!',
    "First come, first served!",
    "This guy gives stupid a bad name!",
    "Stupid is as stupid does!",
    "I knew I should've taken that left turn to Glutinous! Was it something I said? What could possibly go wrong?",
    "Nothing can stop me now!",
    "A penguin saved is a penguin earned.",
    "Do you believe in miracles!?",
    "I win! I win!",
    "I like it!",
    "Surely you jest?",
    "Pilot's license? What for?",
    "Who wrote this stuff?",
    "Another swine mess...",
    "Remember: I am a trained purr-fessional.",
    "Aw, nuts!",
    "Is there a doctor in the house!?",
    "Is the writers' strike over yet?",
    "Go for Baroque!",
    "Ooh, I think I Baroque something!",
    "That's it!",
    "Keep it up, JUST KEEP IT UP!",
    "Haha!",
    "I'll be back!",
    "I am not!",
    "Oh, yeah!",
    "I think so.",
    "Bye-bye...",
    "Alright!",
    "Aaauugh...",
    "The hamhocks strike back!",
    "This is definitely contagious.",
    "That's a neat trick.",
    'Keep this under wrap.',
    "Oh sure, let's all torch the Bubster.",
    "Pilot's license? What for?",
    "Keep it up! Just keep it up!" ,
    "Who do I look like? Flipper?",
    "Nothing can stop me now!",
    "Gimmie, Gimmie, Gimmie!",
    "Grab all the atoms you see!",
    "It's gonna be a bumpy ride.",
    'Just like Mom used to make!',
    "Lucky thing I'm a cartoon.",
    "Now, what would a platform game be without platforms hmm. I wonder if there's any extra lives up there?",
    "Oh look! An arrow! Aren't these game designers wonderful?",
    "Ooh, ooh! This is my FAVORITE part!",
    "So, you wanna be a video game star?",
    "Tag, you're it!",
    "This would've KILLED Arnold!",
    "(Unintelligible) What buttons did you press?",
    "WAKE UP!!!!",
    "Woolie Bully!",
    "YOWZA!!!",
    "Aaagghhh!!!",
    "Air control to the maximum.",
    "And... pounce!",
    "Bobcat in your face!",
    "Bubsy's on a pouncing spree!",
    "Can I get a stunt cat?",
    "Double pounce!",
    "How am I gliding? Hehe. I have no idea.",
    "I like it!",
    "I only regret I have but nine lives to give.",
    "I win!",
    "If you were waiting for the opportune moment, that was it.",
    "I'm gonna knit the biggest sweater ever!",
    "Is water still my kryptonite?",
    "M.C. Bubster the pounce master in the game yeh!",
    "My old enemy: gravity!",
    "No idea how I'm doing this but I like it!",
    "Not flying? Oh yes I am!",
    "One woolie out, and a lot more to go!",
    "Pain is not in my contract!",
    "Pilot's license? What for?",
    "Pounce Pounce Baby",
    "Pouncing really makes me hungry. Is it taco Tuesday yet?",
    "Remember when falling used to kill me?",
    "Stttrrrike one!",
    "Take that, you cotton-gobbling monster!",
    "This is amazing! I love this new ability!",
    "This makes so much sense! Why didn't I think of this before?",
    "Told you I was dead.",
    "We need a plan of attack. My plan: attack!",
    "What could possibly go wrong?",
    "What's wrong with this? Everything!",
    "What? Nuclear Annihilation? The reason the world will end is alien induced yarnball degradation! Mark my words!",
    "When is this going to be over?",
    "Woolies! HA! You're 24 years too late to catch me.",
    "World hunger... Nuclear proliferation... Reality TV... None of those horrors compare to... Yarn ball deprivation!",
    "YAHOO",
    "You have some unfinished business with the Woolies? Well get in line pal, I've been waiting to settle this score since 1993.",

];

module.exports = bubsyArr;